# Generated by Django 5.1.7 on 2025-07-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contactenquiry_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactenquiry',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
